name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust 1.88
        run: rustup toolchain install 1.88.0 --profile minimal
      - name: Test minimum Rust version
        run: cargo +1.88.0 test --locked

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      - name: Test
        run: cargo test --locked
      - name: Build
        run: cargo build --release --locked
